### ISSUE TITLE
Script Error for Channel 8 but not for Channel 5

### ISSUE THREAD

**Issue by khoyek** [GadgetReactor/plugin.video.sgtv#1]
Hi there.

Encountered script error and when checked the log file, found the following.

Appreciate if you can take a look at it.

11:47:03 T:15796 WARNING: CVideoInfoTag::GetDurationFromMinuteString <runtime> should be in minutes. Interpreting '1:28:08' as 1 minutes
11:47:03 T:14428  NOTICE: Thread BackgroundLoader start, auto delete: false
11:47:03 T:15172  NOTICE: Thread JobWorker start, auto delete: true
11:47:05 T:15436  NOTICE: Thread FileCache start, auto delete: false
11:47:10 T:14556  NOTICE: Previous line repeats 2 times.
11:47:10 T:14556  NOTICE: Thread LanguageInvoker start, auto delete: false
11:47:10 T:14556  NOTICE: -->Python Interpreter Initialized<--
11:47:12 T:14556   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'video_url' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\820045\AppData\Roaming\Kodi\addons\plugin.video.sgtv-master\default.py", line 241, in <module>
                                                resolveMSN(url)
                                              File "C:\Users\820045\AppData\Roaming\Kodi\addons\plugin.video.sgtv-master\default.py", line 207, in resolveMSN
                                                video_url=htmlParse(video_url)
                                            UnboundLocalError: local variable 'video_url' referenced before assignment
                                            -->End of Python script error report<--
11:47:12 T:9104   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sgtv/?mode=resolveMSN&url=http%3A%2F%2Fxin.msn.com%2Fen-sg%2Fvideo%2Fcatchup%2Flife-is-beautiful-episode-1%2Fvp-d8bec24c-07a4-423b-b0b7-7bf71e51bd42]
11:47:13 T:15356  NOTICE: Thread FileCache start, auto delete: false
11:47:16 T:8812  NOTICE: Thread BackgroundLoader start, auto delete: false
11:47:17 T:9800  NOTICE: Thread LanguageInvoker start, auto delete: false
11:47:17 T:9800  NOTICE: -->Python Interpreter Initialized<--
11:47:26 T:9800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'video_url' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\820045\AppData\Roaming\Kodi\addons\plugin.video.sgtv-master\default.py", line 241, in <module>
                                                resolveMSN(url)
                                              File "C:\Users\820045\AppData\Roaming\Kodi\addons\plugin.video.sgtv-master\default.py", line 207, in resolveMSN
                                                video_url=htmlParse(video_url)
                                            UnboundLocalError: local variable 'video_url' referenced before assignment
                                            -->End of Python script error report<--
11:47:26 T:9104   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sgtv/?mode=resolveMSN&url=http%3A%2F%2Fxin.msn.com%2Fen-sg%2Fvideo%2Fcatchup%2Flife-is-beautiful-episode-1%2Fvp-d8bec24c-07a4-423b-b0b7-7bf71e51bd42]
11:47:26 T:15404  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by GadgetReactor** [comment]
thanks - i made some changes. will push it to the xbmc repository soon.

**Comment by khoyek** [comment]
Thanks. looking forward for the new release.
